### ISSUE TITLE
Unable to Create Account

### ISSUE THREAD

**Issue by Tloru** [HermesMessenger/HermesDesktop#11]
This issue is probably due to not being able to connect to the server as this app is decentralized, but I'm unable to create an account through the desktop app. After choosing a username and entering a password, the app simply does nothing. After I while, I either run into a 504 gateway timeout or a 503. What's your take on this, is it the application itself or just a side effect of this app's decentralized nature?

(In case you're wondering, I'm running the most recent version of Hermes on Mac OS Mojave on an early 2015 13-inch MacBook Air)

**Comment by spaceface777** [comment]
This issue is occurring because the database we're using disconnected for some reason. We're running the server on a single Raspberry Pi, so the server sometimes crashes due to the very slow server we're using. 

The issue should be fixed already since I restarted the server.

**Comment by Tloru** [comment]
Ok, thank you. I'll try again and tell you if I run into to any other mishaps. 😄
